#include "CutAccuracy/Geometry.hpp"
#include <algorithm>
#include <cmath>
namespace CutAccuracy { namespace {
void appendUnique(std::vector<Vec3>&pts,const Vec3&p,double eps){for(const auto&q:pts)if(nearlyEqual(p,q,eps))return;pts.push_back(p);} Face cleanupFace(Face face,double eps){if(face.empty())return face;Face out;out.reserve(face.size());for(const auto&p:face)if(out.empty()||!nearlyEqual(out.back(),p,eps))out.push_back(p);if(out.size()>1&&nearlyEqual(out.front(),out.back(),eps))out.pop_back();if(out.size()<3)return{};return out;}
}
ConvexPolyhedron ConvexPolyhedron::unitCube(double h){const Vec3 p000{-h,-h,-h},p001{-h,-h,h},p010{-h,h,-h},p011{-h,h,h},p100{h,-h,-h},p101{h,-h,h},p110{h,h,-h},p111{h,h,h};return{{{p000,p100,p110,p010},{p001,p011,p111,p101},{p000,p001,p101,p100},{p010,p110,p111,p011},{p000,p010,p011,p001},{p100,p101,p111,p110}}};}
std::vector<Vec3> ConvexPolyhedron::uniqueVertices(double eps)const{std::vector<Vec3>v;for(const auto&f:faces)for(const auto&p:f)appendUnique(v,p,eps);return v;}
ConvexPolyhedron ConvexPolyhedron::clipped(const Plane&plane,double eps)const{ConvexPolyhedron out;std::vector<Vec3>cap;for(const auto&face:faces){if(face.size()<3)continue;Face cf;for(size_t i=0;i<face.size();++i){const Vec3&a=face[i],&b=face[(i+1)%face.size()];double da=plane.signedDistance(a),db=plane.signedDistance(b);bool ia=da>=-eps,ib=db>=-eps;if(ia)cf.push_back(a);if(ia!=ib){double den=da-db;if(std::abs(den)>eps){double t=std::clamp(da/den,0.0,1.0);Vec3 p=lerp(a,b,t);cf.push_back(p);appendUnique(cap,p,1e-7);}}else{if(std::abs(da)<=eps)appendUnique(cap,a,1e-7);if(std::abs(db)<=eps)appendUnique(cap,b,1e-7);}}cf=cleanupFace(std::move(cf),1e-8);if(cf.size()>=3)out.faces.push_back(std::move(cf));}if(cap.size()>=3){Vec3 c{};for(const auto&p:cap)c+=p;c=c/static_cast<double>(cap.size());Vec3 n=normalized(plane.n),helper=std::abs(n.x)<0.8?Vec3{1,0,0}:Vec3{0,1,0};Vec3 u=normalized(cross(n,helper));if(lengthSq(u)<1e-12)u=normalized(cross(n,{0,0,1}));Vec3 v=cross(n,u);std::sort(cap.begin(),cap.end(),[&](const Vec3&a,const Vec3&b){Vec3 da=a-c,db=b-c;return std::atan2(dot(da,v),dot(da,u))<std::atan2(dot(db,v),dot(db,u));});Face f=cleanupFace(std::move(cap),1e-8);if(f.size()>=3)out.faces.push_back(std::move(f));}return out;}
double ConvexPolyhedron::volume()const{auto verts=uniqueVertices();if(verts.size()<4)return 0;Vec3 c{};for(const auto&p:verts)c+=p;c=c/static_cast<double>(verts.size());double vol=0;for(const auto&f:faces){if(f.size()<3)continue;Vec3 a=f[0]-c;for(size_t i=1;i+1<f.size();++i)vol+=std::abs(dot(a,cross(f[i]-c,f[i+1]-c)))/6.0;}return vol;}
ConvexPolyhedron makeMiniNote(const Vec3&axisIn,bool positive){Vec3 axis=normalized(axisIn);if(lengthSq(axis)<1e-12)axis={0,1,0};Plane p=Plane::throughPoint(axis,{0,0,0});if(!positive)p=p.flipped();return ConvexPolyhedron::unitCube().clipped(p);} ConvexPolyhedron makeDepthSplitMiniNote(const Vec3&axis,bool positive,bool positiveDepth){Plane p=Plane::throughPoint({0,0,1},{0,0,0});if(!positiveDepth)p=p.flipped();return makeMiniNote(axis,positive).clipped(p);}
Vec3 splitAxisForCutDirection(CutDirection d){switch(d){case CutDirection::Up:return{0,1,0};case CutDirection::Down:return{0,-1,0};case CutDirection::Left:return{-1,0,0};case CutDirection::Right:return{1,0,0};case CutDirection::UpRight:return normalized({1,1,0});case CutDirection::UpLeft:return normalized({-1,1,0});case CutDirection::DownLeft:return normalized({-1,-1,0});case CutDirection::DownRight:return normalized({1,-1,0});default:return{0,0,0};}}
Vec3 splitAxisForCutDirection(CutDirection d,double offset){Vec3 axis=splitAxisForCutDirection(d);if(lengthSq(axis)<1e-12||std::abs(offset)<1e-9)return axis;double r=offset*3.14159265358979323846/180.0,c=std::cos(r),s=std::sin(r);return normalized({axis.x*c-axis.y*s,axis.x*s+axis.y*c,0});} bool hasDirectionalSplit(CutDirection d){return lengthSq(splitAxisForCutDirection(d))>1e-12;}
MiniNoteVolumes cutPolyhedronVolumes(const ConvexPolyhedron&poly,const Plane&cut){double total=poly.volume();if(total<=1e-12)return{};double pos=poly.clipped(cut).volume(),neg=std::max(0.0,total-pos);return{pos,neg,total};} MiniNoteVolumes cutMiniNoteVolumes(const Vec3&axis,bool positive,const Plane&cut){return cutPolyhedronVolumes(makeMiniNote(axis,positive),cut);} DepthSplitMiniNoteVolumes cutDepthSplitMiniNoteVolumes(const Vec3&axis,bool positive,const Plane&cut){return{cutPolyhedronVolumes(makeDepthSplitMiniNote(axis,positive,false),cut),cutPolyhedronVolumes(makeDepthSplitMiniNote(axis,positive,true),cut)};}
}
