#include "CutAccuracy/Stats.hpp"
#include <algorithm>
namespace CutAccuracy { namespace { double pct(double e,double m){return m>0?(e/m)*100.0:0.0;} int mult(int v){return std::max(0,v);} ComponentAverage avg(std::size_t n,double sum){return{n,n?sum/static_cast<double>(n)*100.0:0.0};} }
void SaberStats::reset(){*this=SaberStats{};}
void SaberStats::addScored(const ScoredNote&s,int actualMultiplier,int maxMultiplier){if(s.maxScore<=0)return;++notes_;if(s.accuracyEnabled){++accuracySamples_;accuracySum_+=s.accuracyQuality;}if(s.preciseEnabled){++preciseSamples_;preciseSum_+=s.preciseQuality;++upperSamples_;upperSum_+=s.upperPairQuality;++lowerSamples_;lowerSum_+=s.lowerPairQuality;}if(s.centerEnabled){++centerSamples_;centerSum_+=s.centerQuality;}if(s.beforeEnabled){++beforeSamples_;beforeSum_+=s.beforeQuality;}if(s.afterEnabled){++afterSamples_;afterSum_+=s.afterQuality;}int a=mult(actualMultiplier),m=std::max(1,mult(maxMultiplier));rawEarned_+=std::clamp(s.totalScore,0.0,s.maxScore);rawMax_+=s.maxScore;levelEarned_+=std::clamp(s.totalScore,0.0,s.maxScore)*a;levelMax_+=s.maxScore*m;}
void SaberStats::addFixed(double score,double maxScore,int actualMultiplier,int maxMultiplier){if(maxScore<=0)return;++notes_;int a=mult(actualMultiplier),m=std::max(1,mult(maxMultiplier));double s=std::clamp(score,0.0,maxScore);rawEarned_+=s;rawMax_+=maxScore;levelEarned_+=s*a;levelMax_+=maxScore*m;}
void SaberStats::addMiss(double maxScore,int maxMultiplier){if(maxScore<=0)return;++notes_;rawMax_+=maxScore;levelMax_+=maxScore*std::max(1,mult(maxMultiplier));}
SaberAverages SaberStats::averages()const{double raw=pct(rawEarned_,rawMax_),level=pct(levelEarned_,levelMax_);return{notes_,raw,raw,level,avg(accuracySamples_,accuracySum_),avg(preciseSamples_,preciseSum_),avg(centerSamples_,centerSum_),avg(beforeSamples_,beforeSum_),avg(afterSamples_,afterSum_),avg(upperSamples_,upperSum_),avg(lowerSamples_,lowerSum_)};}
SessionAverages SessionStats::averages()const{auto l=left.averages(),r=right.averages();double raw=pct(rawEarned(),rawMax()),level=pct(levelEarned(),levelMax());return{l.notes+r.notes,raw,raw,level,l,r};}
}
